FROM rocker/verse:4.1.3
RUN apt-get update -y && apt-get install -y  make  git libssl-dev libcurl4-openssl-dev  libcurl4-openssl-dev libssl-dev  git libgit2-dev libssl-dev libcurl4-openssl-dev  git  git libxml2-dev pandoc libgit2-dev libssl-dev libicu-dev libcurl4-openssl-dev make zlib1g-dev  make zlib1g-dev  libssl-dev libcurl4-openssl-dev  libxml2-dev  libfontconfig1-dev  libfreetype6-dev  imagemagick  libmagick++-dev  gsfonts  pandoc  libssl-dev  libpng-dev  libicu-dev  libcurl4-openssl-dev  pandoc libicu-dev  pandoc libicu-dev make  libxml2-dev pandoc libicu-dev make  libxml2-dev libssl-dev libicu-dev libcurl4-openssl-dev  libxml2-dev pandoc libicu-dev  libfontconfig1-dev libfreetype6-dev libpng-dev  libfontconfig1-dev libfreetype6-dev  git libgit2-dev libssl-dev libcurl4-openssl-dev make && rm -rf /var/lib/apt/lists/*
RUN mkdir -p /usr/local/lib/R/etc/ /usr/lib/R/etc/
RUN echo "options(renv.config.pak.enabled = TRUE, repos = c(CRAN = 'https://cran.rstudio.com/'), download.file.method = 'libcurl', Ncpus = 4)" | tee /usr/local/lib/R/etc/Rprofile.site | tee /usr/lib/R/etc/Rprofile.site
RUN R -e 'install.packages(c("renv","remotes"))'
COPY renv.lock.prod renv.lock
RUN R -e 'renv::restore()'
