default:
  golem_name: learndfv
  golem_version: 0.0.0.9000
  app_prod: no
production:
  app_prod: yes
dev:
  golem_wd: C:/Users/asger/Documents/Universitet/Bachelor/6 Semester/Dansk Flora/DanskFloraApp
